### ISSUE TITLE
support parsing tags

### ISSUE THREAD

**Issue by yorkie** [weflex/node-orgmode#1]
Like the syntax:

``` org
#+NAME: foobar :prop1 yes
```

Or in multiline:

``` org
#+NAME: foobar
:PROPERTIES:
:prop1:    yes
:prop2:    zoo
:END:
```

**Comment by scottoasis** [comment]
For inlined-syntax, it would looks like:

``` org
#+NAME: foobar :prop1 yes
```

**Comment by yorkie** [comment]
Thanks, updated :-)

**Comment by yorkie** [comment]
@b232wang This should be your first work in weflex, read the source code and try to close this issue, if any problems, let me know here, best of luck :-)

**Comment by yorkie** [comment]
By the way, @scottoasis could you please add @b232wang to our slack?
